image: node:10-stretch

stages:
  - test
  - build

tests:
  stage: test
  script:
    - yarn
    - ./node_modules/jest/bin/jest.js

build:
  stage: build
  only:
    - master
    - tags
  script:
  - yarn
  - yarn global add expo-cli
  - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
  - expo build:android --no-publish
